"""d=alteracao models proprietarios

Revision ID: 27cf2ef03d20
Revises: 4ccb986683e9
Create Date: 2025-07-09 10:09:24.925029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27cf2ef03d20'
down_revision: Union[str, None] = '4ccb986683e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proprietarios', 'rg',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('proprietarios', 'orgao_emissor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('proprietarios', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('proprietarios', 'telefone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('proprietarios', 'endereco',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proprietarios', 'endereco',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('proprietarios', 'telefone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('proprietarios', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('proprietarios', 'orgao_emissor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('proprietarios', 'rg',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###
