"""d=versao inicial02

Revision ID: 4eed4a9de9fd
Revises: fcc25935cdc3
Create Date: 2025-04-27 17:02:33.766282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4eed4a9de9fd'
down_revision: Union[str, None] = 'fcc25935cdc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos_modelo_pdf',
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('conteudo_html', sa.Text(), nullable=False),
    sa.Column('tenant_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_table('inquilinos',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.String(length=10), nullable=False),
    sa.Column('rg', sa.String(length=15), nullable=False),
    sa.Column('orgao_emissor', sa.String(length=50), nullable=False),
    sa.Column('estado_civil', sa.String(length=25), nullable=False),
    sa.Column('profissao_ocupacao', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('nome_pai', sa.String(length=50), nullable=False),
    sa.Column('nome_mae', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('logs',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.String(length=50), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_table('proprietarios',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('rg', sa.String(length=15), nullable=False),
    sa.Column('orgao_emissor', sa.String(length=50), nullable=False),
    sa.Column('estado_civil', sa.String(length=25), nullable=False),
    sa.Column('profissao_ocupacao', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('conta_bancaria', sa.String(length=50), nullable=False),
    sa.Column('pix', sa.String(length=50), nullable=False),
    sa.Column('chave_pix', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('usuarios',
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('imoveis',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('area_total', sa.Float(), nullable=False),
    sa.Column('qtd_quartos', sa.Integer(), nullable=False),
    sa.Column('qtd_suites', sa.Integer(), nullable=False),
    sa.Column('qtd_banheiros', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('aluguel_venda', sa.Enum('aluguel', 'venda', name='alugel_ou_venda'), nullable=False),
    sa.Column('casa_apartamento', sa.Enum('casa', 'apartamento', name='casa_ou_apartamento'), nullable=False),
    sa.Column('tipo_imovel', sa.Enum('residencial', 'comercial', name='tipo_imovel'), nullable=False),
    sa.Column('proprietario_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['proprietario_id'], ['proprietarios.pk_id'], ),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('endereco')
    )
    op.create_table('tokens_dispositivos',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_token', sa.String(length=500), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.pk_id'], ),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('dispositivo_token')
    )
    op.create_table('contratos',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('valor_mensal', sa.Float(), nullable=False),
    sa.Column('taxa_limpeza', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'encerrado', 'pendente', name='status_enum'), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.pk_id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.pk_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.pk_id'], ),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_table('pagamentos',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('valor_pago', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('metodo_pagamento', sa.Enum('PIX', 'Boleto', 'transferência', name='metodo_pagamento'), nullable=True),
    sa.Column('status', sa.Enum('pago', 'pendente', 'atrasado', name='status_pagamento'), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.pk_id'], ),
    sa.PrimaryKeyConstraint('pk_id')
    )
    op.create_table('notificacoes',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('pagamento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_notificacao', sa.Enum('vencimento', 'atraso', 'outro', name='tipo_notificacao'), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.Column('meio_envio', sa.Enum('email', 'whatsApp', 'push', name='meio_notificacao'), nullable=False),
    sa.Column('titulo', sa.String(length=75), nullable=False),
    sa.Column('mensagem', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'enviado-nao-visualizado', 'erro', 'enviado-visualizado', name='status_notificacao'), nullable=False),
    sa.Column('tenant_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamentos.pk_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.pk_id'], ),
    sa.PrimaryKeyConstraint('pk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacoes')
    op.drop_table('pagamentos')
    op.drop_table('contratos')
    op.drop_table('tokens_dispositivos')
    op.drop_table('imoveis')
    op.drop_table('usuarios')
    op.drop_table('proprietarios')
    op.drop_table('logs')
    op.drop_table('inquilinos')
    op.drop_table('contratos_modelo_pdf')
    # ### end Alembic commands ###
