"""d=acrescentar predio em campo casa_apartamento

Revision ID: a8af8d34a73d
Revises: 27cf2ef03d20
Create Date: 2025-07-12 16:09:33.322920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8af8d34a73d'
down_revision: Union[str, None] = '27cf2ef03d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'proprietarios', ['rg'])
    op.create_unique_constraint(None, 'proprietarios', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proprietarios', type_='unique')
    op.drop_constraint(None, 'proprietarios', type_='unique')
    # ### end Alembic commands ###
