"""d=rg nao obrigatorio

Revision ID: fae44dc1c8d6
Revises: a8af8d34a73d
Create Date: 2025-07-15 19:38:13.515111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fae44dc1c8d6'
down_revision: Union[str, None] = 'a8af8d34a73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inquilinos', 'rg',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('inquilinos', 'orgao_emissor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index('rg', table_name='inquilinos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('rg', 'inquilinos', ['rg'], unique=True)
    op.alter_column('inquilinos', 'orgao_emissor',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('inquilinos', 'rg',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###
