from api.routes.contratos.models import ContratoModel
from api.routes.proprietarios.models import ProprietarioModel
from api.routes.imoveis.models import ImovelModel
from api.routes.inquilinos.models import InquilinoModel
from api.routes.usuarios.models.usuario_model import UsuarioModel
from api.routes.tokens_dispositivos.token_model import TokenDispositivoModel
from api.routes.notificacao.models import NotificacaoModel
from api.routes.pagamento.models import PagamentoModel
from api.routes.contrato_pdf_export.models import ContratoModeloPdfModel
from api.routes.tables_logs.models import LogModel
